<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXeQ5ExB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXeQ5ExB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXeQ5ExB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXeQ5ExB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXeQ5ExB\App_KernelDevDebugContainer([
    'container.build_hash' => 'XeQ5ExB',
    'container.build_id' => '7dcee8d5',
    'container.build_time' => 1585496424,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXeQ5ExB');
